services:
  - type: web
    name: trae-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: trae-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100

databases:
  - name: trae-db
    plan: free
    databaseName: trae_database
    user: trae_user